-- APAGAR BANCO DE DADOS
DROP DATABASE IF EXISTS ASS_AQUI;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE ASS_AQUI;

-- CONECTANDO A BASE DE DADOS
USE ASS_AQUI;

-- CRIANDO AS TABELAS
CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL
    ,SENHA VARCHAR(100)
    ,CPF VARCHAR(100)
    ,RG VARCHAR(100)
	,EMAIL VARCHAR(100)
	,TELEFONE VARCHAR(100)
    ,NOME VARCHAR(100)
    ,DTNASCIMENTO VARCHAR(100)
    ,PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE OCORRENCIA(
	IDOCORRENCIA INT NOT NULL
    ,FOTO VARCHAR(100)
    ,DESCRICAO VARCHAR(100)
    ,TITULO VARCHAR(100)
    ,CATEGORIA VARCHAR(100)
    ,COMPLEMENTO VARCHAR(100)
    ,NUMERO_REF VARCHAR(100)
    ,ESTADO VARCHAR(100)
    ,RUA VARCHAR(100)
    ,CEP VARCHAR(100)
    ,CIDADE VARCHAR(100)
    ,PRIMARY KEY (IDOCORRENCIA)
);

CREATE TABLE ASSINATURA(
	IDASSINATURA INT NOT NULL
    ,HASHTAG VARCHAR(100)
    ,DTTIME int
    ,PRIMARY KEY (IDASSINATURA)
);